### ISSUE TITLE
Cleanup (Generated, only with Entitas Asset Store version)

### ISSUE THREAD

**Issue by wangsihao87** [sschmid/Match-One#5]
Somewhere explains about this? I use the github version, after regenerate the code, and theses cleanupsystems are gone,  What's the main difference between the two versions?

**Comment by sschmid** [comment]
The payed Unity Asset Store version used to include additional code generators like for Cleanup and also the Roslyn generators, which work also when there are compiler errors.

As of Feb 2021 the Asset Store version is free:
https://github.com/sschmid/Entitas/issues/973

As of Sep 2022, starting with Entitas 1.14.0, there are no differences anymore between the versions.
The Entitas 1.14.0 GitHub version is now the main version and contains all generators.

Here some details on the current development plans:
https://github.com/sschmid/Entitas/issues/992
