### ISSUE TITLE
Jenny Generation causes compilation errors when the project is opened with Visual Studio for Mac

### ISSUE THREAD

**Issue by AlberGanAvi** [sschmid/Match-One#7]
Jenny Generation causes compilation errors when the project is opened with Visual Studio for Mac.

The zip contains all the project files after opening it with Visual Studio for Mac and after Jenny Generation was executed so it has compilation errors. Also, I had to remove the Library folder because with it the zip was too big to update to GitHub issues.

[Match-One_IDE_VisualStudioForMac_GeneratedBroken 2.zip](https://github.com/sschmid/Match-One/files/9644906/Match-One_IDE_VisualStudioForMac_GeneratedBroken.2.zip)

**Comment by sschmid** [comment]
duplicate https://github.com/sschmid/Entitas/issues/1035
