### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by b4lie** [sschmid/Match-One#9]
Hello, I would like to know about the generation method of 2.0. I found the following error after obtaining the 2.0 example. There is no method to implement IContext. I found that versions before 2.0 inherited Context<T>. I changed it to inherit Context, but it requires passing in the number of components and construction methods. In version 1.41, it is dynamically produced, so what should I do correctly?
![image](https://github.com/sschmid/Match-One/assets/85050927/807fce0d-b584-4420-ac31-6357b2c005a9)

**Comment by DeusExMachina1993** [comment]
@yuliuren do you found a solution?

**Comment by b4lie** [comment]
> @yuliuren你找到解决办法了吗？

yeah 。

**Comment by b4lie** [comment]
> @yuliuren do you found a solution?

2.0 requires the engine version to be greater than 2022.3.x. Then you need to find the dll "Entitas.Generators" in the project and add a "RoslynAnalyzer" tag to it.
![1726713831951](https://github.com/user-attachments/assets/3b76c960-d89b-4361-8d58-d37e4e49ba9e)
